const { requireData } = require('./supabasePracticeRepository');
const { calculateAttemptSummary } = require('./attemptSummary');
function createSupabaseAssessmentRepository(supabase) {
  return Object.freeze({
    async findEligibleAssignment({ assignmentId, studentId }) {
      const row = requireData('assignment lookup', await supabase.from('visualdsa_assessment_assignments').select('id,class_id,module_id,settings,available_from,available_until,status,visualdsa_modules(module_key,version)').eq('id', assignmentId).eq('status', 'published').maybeSingle());
      if (!row) return null;
      const settings = row.settings || {};
      if (Array.isArray(settings.studentIds) && !settings.studentIds.includes(studentId)) return null;
      return { id: row.id, classId: row.class_id, moduleId: row.module_id, moduleKey: row.visualdsa_modules.module_key, moduleVersion: row.visualdsa_modules.version, templateKey: settings.templateKey, attemptLimit: Number(settings.attemptLimit || 1), timeLimitMinutes: Number(settings.timeLimitMinutes || 0), availableFrom: row.available_from, availableUntil: row.available_until, scoringVersion: settings.scoringVersion || '1.0.0' };
    },
    async countAttempts({ assignmentId, studentId }) {
      const result = await supabase.from('visualdsa_assessment_attempts').select('id', { count: 'exact', head: true }).eq('assignment_id', assignmentId).eq('student_id', studentId);
      if (result.error) requireData('attempt count', result);
      return result.count || 0;
    },
    async createAttempt({ identity, assignment, attemptNumber, problem, now }) {
      const template = requireData('template lookup', await supabase.from('visualdsa_problem_templates').select('id').eq('template_key', assignment.templateKey).eq('is_active', true).single());
      const instance = requireData('problem creation', await supabase.from('visualdsa_problem_instances').insert({ template_id: template.id, problem_seed: problem.seed, module_version: problem.moduleVersion, public_input: problem.input, validation_data: { expectedStates: problem.expectedStates }, expected_steps_hash: problem.expectedStepsHash }).select('id').single());
      const expiresAt = assignment.timeLimitMinutes ? new Date(now.getTime() + assignment.timeLimitMinutes * 60000).toISOString() : null;
      const row = requireData('attempt creation', await supabase.from('visualdsa_assessment_attempts').insert({ assignment_id: assignment.id, problem_instance_id: instance.id, user_id: identity.userId, student_id: identity.studentId, class_id: assignment.classId, attempt_number: attemptNumber, status: 'in_progress', module_version: assignment.moduleVersion, scoring_version: assignment.scoringVersion, started_at: now.toISOString(), expires_at: expiresAt }).select('id,attempt_number,status,expires_at').single());
      return { attemptId: row.id, attemptNumber: row.attempt_number, status: row.status, moduleKey: assignment.moduleKey, moduleVersion: assignment.moduleVersion, problem: { seed: problem.seed, input: problem.input }, expiresAt: row.expires_at };
    },
    async findAttempt(id) {
      const row = requireData('attempt lookup', await supabase.from('visualdsa_assessment_attempts').select('id,user_id,student_id,status,problem_instance_id,expires_at,visualdsa_assessment_assignments(settings,visualdsa_modules(module_key))').eq('id', id).maybeSingle());
      return row ? { id: row.id, userId: row.user_id, studentId: row.student_id, status: row.status, problemInstanceId: row.problem_instance_id, expiresAt: row.expires_at, templateKey: row.visualdsa_assessment_assignments.settings.templateKey, moduleKey: row.visualdsa_assessment_assignments.visualdsa_modules.module_key } : null;
    },
    async loadProblem(id) { const row = requireData('problem lookup', await supabase.from('visualdsa_problem_instances').select('problem_seed,public_input,validation_data,module_version').eq('id', id).single()); return { seed: row.problem_seed, input: row.public_input, expectedStates: row.validation_data.expectedStates, moduleVersion: row.module_version }; },
    async getResumeView(attempt) { const [problemResult,actionsResult]=await Promise.all([supabase.from('visualdsa_problem_instances').select('problem_seed,public_input').eq('id',attempt.problemInstanceId).single(),supabase.from('visualdsa_attempt_actions').select('step_number').eq('assessment_attempt_id',attempt.id).order('created_at')]);const row=requireData('problem resume lookup',problemResult);const actions=requireData('assessment resume actions',actionsResult);return { attemptId: attempt.id, status: attempt.status, moduleKey:attempt.moduleKey, problem: { seed: row.problem_seed, input: row.public_input }, submittedSteps:actions.map(item=>item.step_number), expiresAt: attempt.expiresAt }; },
    async findAssessmentAction(id) { const row = requireData('assessment action lookup', await supabase.from('visualdsa_attempt_actions').select('student_id,assessment_attempt_id,is_correct,misconception_code').eq('client_event_id', id).maybeSingle()); return row ? { studentId: row.student_id, assessmentAttemptId: row.assessment_attempt_id, result: { accepted: true, isCorrect: row.is_correct, misconceptionCode: row.misconception_code } } : null; },
    async appendAssessmentAction({ identity, attempt, action, validation }) { const row = requireData('assessment action creation', await supabase.from('visualdsa_attempt_actions').insert({ client_event_id: action.clientEventId, user_id: identity.userId, student_id: identity.studentId, assessment_attempt_id: attempt.id, step_number: action.stepNumber, action_type: action.actionType, submitted_payload: action.payload, is_correct: validation.isCorrect, misconception_code: validation.misconceptionCode, validation_version: validation.validationVersion }).select('is_correct,misconception_code').single()); return { result: { accepted: true, isCorrect: row.is_correct, misconceptionCode: row.misconception_code } }; },
    async listAssessmentActions(id) { const rows = requireData('assessment action list', await supabase.from('visualdsa_attempt_actions').select('step_number,is_correct,misconception_code,hint_level').eq('assessment_attempt_id', id).order('created_at')); return rows.map((row) => ({ stepNumber:row.step_number,hintLevel:row.hint_level,validation: { isCorrect: row.is_correct, misconceptionCode: row.misconception_code } })); },
    async gradeAndLock({ attempt, score, actions }) { const row = requireData('attempt grading', await supabase.from('visualdsa_assessment_attempts').update({ status: 'graded', score: score.raw, maximum_score: score.maximum, percentage_score: score.percentage, submitted_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq('id', attempt.id).in('status', ['started','in_progress','paused']).select('id,status,score,maximum_score,percentage_score,student_id,module_version').maybeSingle()); if (!row) throw Object.assign(new Error('Attempt already submitted.'), { code: 'ATTEMPT_ALREADY_SUBMITTED' }); const summary=calculateAttemptSummary(actions); requireData('attempt summary',await supabase.from('visualdsa_attempt_summaries').upsert({assessment_attempt_id:row.id,student_id:row.student_id,module_key:attempt.templateKey.split('-')[0],total_scored_steps:summary.totalScoredSteps,correct_first_responses:summary.correctFirstResponses,correct_final_responses:summary.correctFinalResponses,hints_used:summary.hintsUsed,retries:summary.retries,first_attempt_accuracy:summary.firstAttemptAccuracy,final_accuracy:summary.finalAccuracy,percentage_score:score.percentage,misconception_counts:summary.misconceptionCounts,calculation_version:'1.0.0'},{onConflict:'assessment_attempt_id'})); return { attemptId: row.id, status: row.status, score: { raw: Number(row.score), maximum: Number(row.maximum_score), percentage: Number(row.percentage_score) } }; }
  });
}
module.exports = { createSupabaseAssessmentRepository };
