begin;
create or replace function visualdsa_recalculate_student_mastery(p_student text,p_module text,p_class text) returns void language plpgsql security definer set search_path=public as $$
declare assessment numeric;practice numeric;completion numeric;evidence integer;score numeric;status text;
begin
 select avg(a.percentage_score),count(*) into assessment,evidence from visualdsa_assessment_attempts a join visualdsa_assessment_assignments x on x.id=a.assignment_id join visualdsa_modules m on m.id=x.module_id where a.student_id=p_student and m.module_key=p_module and a.status='graded';
 select avg(case when first_action.is_correct then 100 else 0 end) into practice from(select distinct on(ac.practice_session_id,ac.step_number) ac.is_correct from visualdsa_attempt_actions ac join visualdsa_practice_sessions s on s.id=ac.practice_session_id join visualdsa_modules m on m.id=s.module_id where ac.student_id=p_student and m.module_key=p_module order by ac.practice_session_id,ac.step_number,ac.created_at)first_action;
 select 100.0*count(*)filter(where s.status='completed')/nullif(count(*),0) into completion from visualdsa_practice_sessions s join visualdsa_modules m on m.id=s.module_id where s.student_id=p_student and m.module_key=p_module;
 assessment:=coalesce(assessment,0);practice:=coalesce(practice,0);completion:=coalesce(completion,0);evidence:=evidence+(select count(*) from visualdsa_practice_sessions s join visualdsa_modules m on m.id=s.module_id where s.student_id=p_student and m.module_key=p_module and s.status='completed');score:=round(assessment*.7+practice*.2+completion*.1,2);status:=case when evidence=0 then'insufficient_evidence' when score>=85 then'mastered' when score>=75 then'proficient' when score>=60 then'developing' else'needs_review'end;
 insert into visualdsa_topic_mastery(student_id,class_id,module_key,mastery_score,mastery_status,assessment_component,practice_component,completion_component,evidence_count,calculation_version,last_evidence_at,calculated_at)values(p_student,p_class,p_module,case when evidence=0 then null else score end,status,assessment*.7,practice*.2,completion*.1,evidence,'mastery-v1',now(),now())on conflict(student_id,class_id,module_key)do update set mastery_score=excluded.mastery_score,mastery_status=excluded.mastery_status,assessment_component=excluded.assessment_component,practice_component=excluded.practice_component,completion_component=excluded.completion_component,evidence_count=excluded.evidence_count,calculation_version=excluded.calculation_version,last_evidence_at=excluded.last_evidence_at,calculated_at=excluded.calculated_at;
end $$;
create or replace function visualdsa_summary_mastery_trigger()returns trigger language plpgsql security definer set search_path=public as $$ declare cls text;begin select class_id into cls from visualdsa_assessment_attempts where id=new.assessment_attempt_id;perform visualdsa_recalculate_student_mastery(new.student_id,new.module_key,cls);return new;end $$;
drop trigger if exists trg_visualdsa_summary_mastery on visualdsa_attempt_summaries;
create trigger trg_visualdsa_summary_mastery after insert or update on visualdsa_attempt_summaries for each row execute function visualdsa_summary_mastery_trigger();
commit;
