const { createAssessmentService } = require('../../app/visualdsa/assessmentService');
const identity = { userId: 'u1', studentId: 's1' };
const active = { id: 'a1', userId: 'u1', studentId: 's1', status: 'in_progress', problemInstanceId: 'p1', templateKey: 'array-insert-v1' };
function setup(overrides = {}) {
  const repository = { findEligibleAssignment: jest.fn(async () => ({ id: 'as1', moduleKey: 'arrays', templateKey: 'array-insert-v1', attemptLimit: 2 })), countAttempts: jest.fn(async () => 0), createAttempt: jest.fn(async (x) => x), findAttempt: jest.fn(async () => active), getResumeView: jest.fn(async () => ({ attemptId: 'a1', currentStep: 1 })), findAssessmentAction: jest.fn(async () => null), loadProblem: jest.fn(async () => ({ expectedStates: [{}] })), appendAssessmentAction: jest.fn(async ({ validation }) => ({ result: validation })), listAssessmentActions: jest.fn(async () => [{ validation: { isCorrect: true } }, { validation: { isCorrect: false } }]), gradeAndLock: jest.fn(async ({ score }) => ({ status: 'graded', score })), ...overrides };
  const problemEngine = { createSeed: jest.fn(() => 'seed'), generateProblem: jest.fn(() => ({ seed: 'seed' })), validateAction: jest.fn(() => ({ accepted: true, isCorrect: true })) };
  return { repository, problemEngine, service: createAssessmentService({ repository, problemEngine }) };
}
describe('VisualDSA assessment lifecycle', () => {
  test('starts eligible attempts with server seed and next attempt number', async () => { const { service, repository } = setup({ countAttempts: jest.fn(async () => 1) }); const result = await service.start({ identity, assignmentId: 'as1' }); expect(result.attemptNumber).toBe(2); expect(repository.createAttempt).toHaveBeenCalled(); });
  test('enforces availability and attempt limits', async () => { await expect(setup({ countAttempts: jest.fn(async () => 2) }).service.start({ identity, assignmentId: 'as1' })).rejects.toMatchObject({ code: 'ATTEMPT_LIMIT_REACHED' }); await expect(setup({ findEligibleAssignment: jest.fn(async () => null) }).service.start({ identity, assignmentId: 'as1' })).rejects.toMatchObject({ code: 'ASSIGNMENT_NOT_AVAILABLE' }); });
  test('enforces authoritative class enrollment before creating an attempt', async () => { const repository=setup().repository;const service=createAssessmentService({repository,problemEngine:setup().problemEngine,authorizeEnrollment:jest.fn(async()=>false)});await expect(service.start({identity,assignmentId:'as1'})).rejects.toMatchObject({code:'ASSIGNMENT_NOT_AVAILABLE'});expect(repository.createAttempt).not.toHaveBeenCalled(); });
  test('resumes only owned active unexpired attempts', async () => { expect(await setup().service.resume({ identity, attemptId: 'a1' })).toEqual({ attemptId: 'a1', currentStep: 1 }); await expect(setup({ findAttempt: jest.fn(async () => ({ ...active, studentId: 'other' })) }).service.resume({ identity, attemptId: 'a1' })).rejects.toMatchObject({ code: 'ATTEMPT_ACCESS_DENIED' }); });
  test('validates actions server-side, hides correctness, and handles only same-owner duplicates', async () => { const first = setup(); expect(await first.service.submitAction({ identity, attemptId: 'a1', action: { clientEventId: 'e', stepNumber: 0 } })).toEqual({accepted:true,duplicate:false}); const duplicate = setup({ findAssessmentAction: jest.fn(async () => ({ studentId: 's1', assessmentAttemptId: 'a1', result: { accepted: true,isCorrect:true } })) }); expect(await duplicate.service.submitAction({ identity, attemptId: 'a1', action: { clientEventId: 'e' } })).toEqual({ accepted: true, duplicate: true }); const foreign = setup({ findAssessmentAction: jest.fn(async () => ({ studentId: 'other', assessmentAttemptId: 'foreign', result: { accepted: true } })) }); await expect(foreign.service.submitAction({ identity, attemptId: 'a1', action: { clientEventId: 'e' } })).rejects.toMatchObject({ code: 'ATTEMPT_ACCESS_DENIED' }); });
  test('locks submitted attempts and calculates official score', async () => { const { service, repository } = setup(); expect(await service.submit({ identity, attemptId: 'a1' })).toEqual({ status: 'graded', score: { raw: 1, maximum: 2, percentage: 50 } }); expect(repository.gradeAndLock).toHaveBeenCalled(); await expect(setup({ findAttempt: jest.fn(async () => ({ ...active, status: 'graded' })) }).service.submit({ identity, attemptId: 'a1' })).rejects.toMatchObject({ code: 'ATTEMPT_ALREADY_SUBMITTED' }); });
});
