const bst=require('../../public/js/visualdsa/modules/bst/bstModule');
describe('BST module',()=>{
 test('inserts root, left, right, and deeper leaves with valid parents',()=>{expect(bst.generateSteps({values:[20,10,30,5,15],operation:'insert',target:12}).at(-1)).toEqual(expect.objectContaining({phase:'inserted',parentId:'node-15',childSide:'left'}));});
 test('searches root, finds descendants, and confirms missing at null',()=>{expect(bst.generateSteps({values:[20,10,30],operation:'search',target:20}).at(-1).phase).toBe('found');expect(bst.generateSteps({values:[20,10,30],operation:'search',target:99}).at(-1).phase).toBe('not-found');});
 test.each([['preorder',[20,10,5,15,30]],['inorder',[5,10,15,20,30]],['postorder',[5,15,10,30,20]]])('%s traversal is correct',(traversal,expected)=>expect(bst.visitOrder(bst.buildTree([20,10,30,5,15]),traversal)).toEqual(expected));
 test('rejects duplicates and invalid bounds',()=>{expect(bst.validateInput({values:[2,2],operation:'search',target:2}).valid).toBe(false);expect(bst.validateInput({values:[],operation:'search',target:2}).valid).toBe(false);});
 test('supports left and right skewed trees and negative values',()=>{expect(bst.visitOrder(bst.buildTree([3,2,1]),'inorder')).toEqual([1,2,3]);expect(bst.visitOrder(bst.buildTree([-3,-2,-1]),'inorder')).toEqual([-3,-2,-1]);});
 test('classifies BT01 through BT10',()=>{const state=bst.generateSteps({values:[20,10],operation:'search',target:10})[1];expect(bst.validateStudentAction({direction:'right'},state).misconceptionCode).toBe('BT01');const flags=[['wrongParent','BT02'],['brokenConnection','BT03'],['duplicateAccepted','BT04'],['depthHeightConfusion','BT06'],['comparedWithRootAgain','BT07'],['ignoredSubtree','BT08'],['inorderAsPreorder','BT09'],['stoppedBeforeNull','BT10']];flags.forEach(([k,c])=>expect(bst.classifyError({[k]:true},state)).toBe(c));const visit=bst.generateSteps({values:[2,1,3],operation:'traverse',traversal:'inorder'})[1];expect(bst.validateStudentAction({value:99},visit).misconceptionCode).toBe('BT05');});
});
