const { createEventService } = require('../../app/visualdsa/eventService');
const identity = { userId: 'u1', studentId: 's1' };
const event = { eventId: '123e4567-e89b-12d3-a456-426614174000', eventType: 'module_opened' };
const context = { lessonSlug: 'arrays', moduleKey: 'arrays', moduleVersion: '1.0.0', mode: 'practice', responseTimeMs: 100 };
describe('VisualDSA event service', () => {
  test('stores server-derived identity for non-scored interaction events', async () => { const repository={findByEventId:jest.fn(async()=>null),append:jest.fn(async x=>x)}; const result=await createEventService(repository).ingest({identity,event,context}); expect(result.duplicate).toBe(false); expect(repository.append).toHaveBeenCalledWith(expect.objectContaining({studentId:'s1',misconceptionCode:null,isCorrect:null})); });
  test('is idempotent for owned events', async () => { const repository={findByEventId:jest.fn(async()=>({eventId:event.eventId,studentId:'s1'}))}; expect(await createEventService(repository).ingest({identity,event,context})).toEqual({eventId:event.eventId,duplicate:true}); });
  test('rejects cross-user duplicates and client-provided scored evidence', async () => { await expect(createEventService({findByEventId:async()=>({studentId:'other'})}).ingest({identity,event,context})).rejects.toMatchObject({code:'EVENT_ACCESS_DENIED'}); await expect(createEventService({findByEventId:async()=>null}).ingest({identity,event,context:{...context,isCorrect:true}})).rejects.toMatchObject({code:'INVALID_INPUT'}); });
  test('rejects unknown modules, invalid versions, and oversized metadata', async () => { const service=createEventService({findByEventId:async()=>null}); await expect(service.ingest({identity,event,context:{...context,moduleKey:'unknown'}})).rejects.toMatchObject({code:'INVALID_INPUT'}); await expect(service.ingest({identity,event,context:{...context,moduleVersion:'latest'}})).rejects.toMatchObject({code:'INVALID_INPUT'}); await expect(service.ingest({identity,event:{...event,metadata:{value:'x'.repeat(9000)}},context})).rejects.toMatchObject({code:'INVALID_INPUT'}); });
  test('authorizes class attribution against enrollment',async()=>{const repository={findByEventId:async()=>null,append:jest.fn(async row=>row)};const denied=createEventService(repository,{authorizeEnrollment:async()=>false});await expect(denied.ingest({identity,event,context:{...context,classId:'507f1f77bcf86cd799439011'}})).rejects.toMatchObject({code:'EVENT_ACCESS_DENIED'});const allowed=createEventService(repository,{authorizeEnrollment:async()=>true});await allowed.ingest({identity,event,context:{...context,classId:'507f1f77bcf86cd799439011'}});expect(repository.append).toHaveBeenCalledWith(expect.objectContaining({classId:'507f1f77bcf86cd799439011'}));});
});
